name: Publish Package to npmjs
on:
  workflow_run:
    workflows: ["Playwright"]
    types:
      - completed
    branches:
      - main
jobs:
  build:
    if: startsWith(github.event.workflow_run.head_commit.message, 'v') && contains(github.event.workflow_run.head_commit.message, '.')
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build the library
        run: npm run build
      - name: Publish to npmjs
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
